;====================================================================
; Main.asm file generated by New Project wizard
; txt coding:	utf-8
;
; Created:   Чт авг 13 2020
; Processor: Attini13
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS	|	Определения
;====================================================================

#include "const_13.inc" ;.INCLUDE 
#include "macro_13.inc"


; ____________Настройка_параметров_____________
; ___________________Setup_____________________
freq 9	;MHz
testmode 1 ; 1 = test mode (3s), 0 = prod. mode (25min)

;====================================================================
; VARIABLES	|	Переменные
;====================================================================

.def temp = r16

;====================================================================
; RESET and INTERRUPT VECTORS	|	Сброс и векторы прерываний
;====================================================================

    rjmp	RESET	    ;	Reset	Handler	
    rjmp	EXT_INT0	;	IRQ0	Handler	
    reti    ;rjmp	PCINT0i	    ;	PCINT0	Handler	
    rjmp	TIM0_OVF	;	Timer0	Overflow	Handler
    reti    ;rjmp	EE_RDY	    ;	EEPROM	Ready	Handler
    reti    ;rjmp	ANA_COMP	;	Analog	Comparator	Handler
    reti    ;rjmp	TIM0_COMPA	;	Timer0	CompareA	Handler
    reti    ;rjmp	TIM0_COMPB	;	Timer0	CompareB	Handler
    reti    ;rjmp	WATCHDOG	;	Watchdog	Interrupt	Handler
    reti    ;rjmp	ADCi        ;	ADC	Conversion	Handler

;====================================================================
; CODE SEGMENT
;====================================================================

EXT_INT0:
    ;
reti

TIM0_OVF:
    ;
reti

reset:
    tout SPL, low(RAMEND)   ; Set Stack Pointer to top of RAM

    sei

loop:
    ;sleep
    rjmp loop